site_name: GCSS-Army User Guide

extra_css:
  - stylesheets/extra.css

theme: 
  palette: 
    # Palette toggle for light mode
      scheme: main
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode


    # Palette toggle for dark mode
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.footer

  

extra:
  generator: false

copyright: Copyright &copy; 2024 - Ernst & Young

plugins:
  - offline
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
