site_name: GCSS-Army User Guide

extra_css:
  - stylesheets/extra.css

theme:
  palette: 

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
    - scheme: light
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
    - scheme: dark
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.footer

  

extra:
  generator: false

copyright: Copyright &copy; 2024 - Ernst & Young

plugins:
  - offline
  - mkdocs-nav-weight:
      section_renamed: false
      index_weight: -10
      warning: true
      reverse: false
      headless_included: false

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
